spring:
  application:
    name: photoshare

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/photoshare}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # none / validate / update / create-drop / create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

    web:
      resources:
        static-locations: file:./uploads/

  data:
    redis:
      host:  ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      password: ${SPRING_REDIS_PASSWORD:}
      timeout: 60000

jwt:
  secret: YourVeryLongAndSecureSecretKeyAtLeast256BitsForHS256Algorithm
  access-token-expiration: 900000 # 15 minutes
  refresh-token-expiration: 2592000000 # 30 days
